### PR TITLE
added fallback using reflection for backward-compatibility

### LINKED ISSUE #1572: NoSuchMethodError: PartitionedFileUtil$.splitFiles when running with Spark 3.5.4
### Describe the bug

The signature of PartitionedFileUtil$.splitFiles changed in Spark 3.5.5, and Comet was updated to use it in #1565, so it is now not compatible with 3.5.4.

This could be fixed with using different shims for the patch-level version (affecting release engineering) or by using reflection within the 3.5 shim.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by YanivKunda**
## Which issue does this PR close?

Closes #1572

## Rationale for this change

Users with older 3.5.x versions before Spark 3.5.5 should be able using the latest comet version.

## What changes are included in this PR?

Modifying the 3.5 `ShimCometScanExec` shim to fallback to reflection with the previous method signatures if the latest is not found.

## How are these changes tested?

Ran `mvn test` with the `spark-3.5` profile.
Added 3.5.4 to the matrix of tested spark versions in `spark_sql_test.yml`

### CODE REVIEW

File: .github/workflows/spark_sql_test.yml [hunk 1]
```diff
@@ -45,7 +45,7 @@ jobs:
       matrix:
         os: [ubuntu-24.04]
         java-version: [11]
-        spark-version: [{short: '3.4', full: '3.4.3'}, {short: '3.5', full: '3.5.5'}]
+        spark-version: [{short: '3.4', full: '3.4.3'}, {short: '3.5', full: '3.5.4'}, {short: '3.5', full: '3.5.5'}]
```
Comment (kazuyukitanimura) [inline .github/workflows/spark_sql_test.yml:48]: Since we advanced the minimum version to 3.5.5, I am not sure if we should add back 3.5.4 tests.
SQL tests can be done here, but tests in Comet are not done with 3.5.4 anymore.

If we decide to support 3.5.4, I would vote for doing it by adding a maven profile.

Comment (YanivKunda) [reply .github/workflows/spark_sql_test.yml:48]: Adding a maven profile using spark 3.5.4 will break compilation for the 3.5 shim -
So to support both 3.5.4 and 3.5.5 in compilation we will need either separate shims for each patch version,
or the 3.5 shim to support all versions through reflection.

Comment (kazuyukitanimura) [reply .github/workflows/spark_sql_test.yml:48]: I would say we should create a separate Shims for Spark 3.5.4 where it is necessary. I know it is right now we only do profile at 3.4, 3.5, 4.0 level. but I observed a couple of API changes between patch version changes.

Comet Release for 3.5 does not mean that it works with all 3.5.x, currently. Now the minimum version will be 3.5.5 in the next release. Either we drop the 3.5.4 support, or create a new profile.

Comment (YanivKunda) [reply .github/workflows/spark_sql_test.yml:48]: I went for the reflection approach after [my post-merge discussion](https://github.com/apache/datafusion-comet/pull/1565#discussion_r2011249870) with @wForget in #1565 -
since creating different shims for 3.5.4 also means a different release for 3.5.4, which might cause confusion for users.
Since I did the upgrade to 3.5.5 separately, dropping support for 3.5.4 simply means discarding this PR.

Comment (wForget) [reply .github/workflows/spark_sql_test.yml:48]: We don't need to add 3.5.4 ci, just make sure it can be compiled successfully. Or how about deleting it after verification in this pr?

File: spark/src/main/spark-3.5/org/apache/spark/sql/comet/shims/ShimCometScanExec.scala [hunk 2]
```diff
@@ -55,15 +55,48 @@ trait ShimCometScanExec {
   protected def isNeededForSchema(sparkSchema: StructType): Boolean = false
 
   protected def getPartitionedFile(f: FileStatusWithMetadata, p: PartitionDirectory): PartitionedFile =
-    PartitionedFileUtil.getPartitionedFile(f, f.getPath, p.values)
+    try {
+      PartitionedFileUtil.getPartitionedFile(f, f.getPath, p.values)
+    } catch {
+      case _: NoSuchMethodError =>
```
Comment (wForget) [inline spark/src/main/spark-3.5/org/apache/spark/sql/comet/shims/ShimCometScanExec.scala:61]: How about directly judging the spark version? Like:
```
if (org.apache.spark.SPARK_VERSION_SHORT >= "3.5.5") {
  ... for spark 3.5.5+
} else {
  ... for spark 3.5.4
}
```

File: .github/workflows/spark_sql_test.yml (hunk 1 above)
Comment (YanivKunda) [reply .github/workflows/spark_sql_test.yml:48]: But it can't be compiled succesfully - for the same reason 3.5.5 couldn't be compiled when the 3.5 shims were compiled against 3.5.4...

File: spark/src/main/spark-3.5/org/apache/spark/sql/comet/shims/ShimCometScanExec.scala (hunk 2 above)
Comment (YanivKunda) [reply spark/src/main/spark-3.5/org/apache/spark/sql/comet/shims/ShimCometScanExec.scala:61]: And keeping the current code paths? (i.e. compiled code for 3.5.5, else reflection)
That is more explicit, but I'm not sure it brings any benefit.
The advantage of the try-catch idea that in case this param will go away in 3.5.6 (like it did in 4.0.0-preview1/2, while it's back in main...) this will remain backward and forward-compatible.

Comment (wForget) [reply spark/src/main/spark-3.5/org/apache/spark/sql/comet/shims/ShimCometScanExec.scala:61]: I prefer to define reflection for each version. Some similar implementations:

https://github.com/apache/iceberg/blob/aa4ed6041b2e4555e222eb587d5055be163f362c/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveClientPool.java#L37-L48

Comment (Kontinuation) [reply spark/src/main/spark-3.5/org/apache/spark/sql/comet/shims/ShimCometScanExec.scala:61]: I prefer maintaining compatibility with more Spark patch versions to increase its adoptability. If it is known to not work with Spark <=3.5.4, we'd better explicitly document it in [Supported Spark Versions]( https://datafusion.apache.org/comet/user-guide/installation.html#supported-spark-versions).

Comment (andygrove) [reply spark/src/main/spark-3.5/org/apache/spark/sql/comet/shims/ShimCometScanExec.scala:61]: I agree that we should support multiple 3.5.x versions. Some users do not have control over the minor Spark version they use. There isn't any technical reason why we cannot maintain diff files for multiple Spark versions and test multiple versions in CI.

Comment (YanivKunda) [reply spark/src/main/spark-3.5/org/apache/spark/sql/comet/shims/ShimCometScanExec.scala]: Added a commit to always invoke the two methods differing between 3.5.x versions using reflection.

**Review by andygrove — APPROVED** [review]
LGTM pending CI. Thanks @YanivKunda. I filed a follow on https://github.com/apache/datafusion-comet/issues/1579 for clarifying our policy for supported Spark versions and continuing the discussion about which versions we should test in CI and for updating the documentation to list the specific versions that we support.

File: spark/src/main/spark-3.5/org/apache/spark/sql/comet/shims/ShimCometScanExec.scala (hunk 2 above)
Comment (andygrove) [reply spark/src/main/spark-3.5/org/apache/spark/sql/comet/shims/ShimCometScanExec.scala]: > Reflection is ok with me. I just wanted to make sure we dropped 3.5.4 support If we decide to support 3.5.4 as community, I think we should test with 3.5.4 (downgrade in pom) all the way

@kazuyukitanimura I filed https://github.com/apache/datafusion-comet/issues/1579 to continue this discussion.

**Comment by YanivKunda** [comment]
I see the tests passed for both 3.5.4 and 3.5.5 - which cover the two braches in my change.
Will that suffice?

**Comment by andygrove** [comment]
> I see the tests passed for both 3.5.4 and 3.5.5 - which cover the two braches in my change. Will that suffice?

Yes, I think this is sufficient for now. I created a follow on PR to explain that 3.5.4 is not fully tested in CI.

https://github.com/apache/datafusion-comet/pull/1580
