### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.spark.sql.execution.FileSourceScanExec.copy$default$9()

### ISSUE THREAD

**Issue by SemyonSinchenko** [apache/datafusion-comet#190]
### Describe the bug

I want to try Comet on Databricks.
I built Comet for Spark 3.4 (`-Prelease -Pspark-3.4`), added it to the jars via init-script, added all needed configurations (`spark conf`). When I am running any query on delta-tables, it tends to the following:
```
com.databricks.backend.common.rpc.SparkDriverExceptions$SQLExecutionException: java.lang.NoSuchMethodError: org.apache.spark.sql.execution.FileSourceScanExec.copy$default$9()Z
	at org.apache.spark.sql.comet.CometScanExec$.apply(CometScanExec.scala:442)
	at org.apache.comet.CometSparkSessionExtensions$CometScanRule$$anonfun$apply$5.applyOrElse(CometSparkSessionExtensions.scala:127)
	at org.apache.comet.CometSparkSessionExtensions$CometScanRule$$anonfun$apply$5.applyOrElse(CometSparkSessionExtensions.scala:77)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:465)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:69)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:465)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$3(TreeNode.scala:470)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren(TreeNode.scala:1269)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren$(TreeNode.scala:1268)
	at org.apache.spark.sql.execution.FilterExec.mapChildren(basicPhysicalOperators.scala:216)
```

### Steps to reproduce

1. Built Comet for spark 3.4
2. Add init-script to Databricks cluster, that adds Comet-JAR to `/databricks/jars`
3. Run any query on delta-tables

### Expected behavior

Comet is working on Databricks 13.3 LTS (Spark 3.4.1, Scala 2.12). Comet fallback to delta-io for reading delta-tables maybe?

### Additional context

I can provide more extended stack-trace, but there is nothing special before lines above, only catalyst-calls.

**Comment by viirya** [comment]
> com.databricks.backend.common.rpc.SparkDriverExceptions$SQLExecutionException: java.lang.NoSuchMethodError: org.apache.spark.sql.execution.FileSourceScanExec.copy$default$9()Z

Hmm, it looks like Databricks Spark changes the constructor of `FileSourceScanExec`? But we cannot look at Databricks Spark source code.

**Comment by SemyonSinchenko** [comment]
> Hmm, it looks like Databricks Spark changes the constructor of FileSourceScanExec? But we cannot look at Databricks Spark source code.

I can raise this question to Databricks support. I just want to be sure that the problem is actually in Databrikcs, not Comet.

**Comment by viirya** [comment]
I cannot test it, but if the issue is due to calling changed constructor of `FileSourceScanExec`, I think we can change the call to `makeCopy`.

If you can test the patch, please let us know if it works. Thanks.

**Comment by SemyonSinchenko** [comment]
I tried and error was changed :)
```
com.databricks.backend.common.rpc.SparkDriverExceptions$SQLExecutionException: java.lang.NoSuchMethodError: org.apache.spark.sql.execution.DataSourceScanExec.$init$(Lorg/apache/spark/sql/execution/DataSourceScanExec;)V
	at org.apache.spark.sql.comet.CometScanExec.<init>(CometScanExec.scala:63)
	at org.apache.spark.sql.comet.CometScanExec$.apply(CometScanExec.scala:476)
	at org.apache.comet.CometSparkSessionExtensions$CometScanRule$$anonfun$apply$5.applyOrElse(CometSparkSessionExtensions.scala:127)
	at org.apache.comet.CometSparkSessionExtensions$CometScanRule$$anonfun$apply$5.applyOrElse(CometSparkSessionExtensions.scala:77)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:465)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:69)
```
I have zero ideas whats wrong with this Databricks Runtime... I was able to run Comet on DBR 12.2 LTS (Spark 3.3.2) and got another, GLIBC/Native related problem. So, it looks like the problem is only in DBR 13.3...

**Comment by SemyonSinchenko** [comment]
Databricks support told me that DBR 13.3 should be fully compatible with all the public API of OSS Spark, but I guess that they backported some patches from 3.5. I will check PRs and changes to try to understand what could they backported...

**Comment by viirya** [comment]
Hmm, as the proposed patch can fix the original error:

```
com.databricks.backend.common.rpc.SparkDriverExceptions$SQLExecutionException: java.lang.NoSuchMethodError: org.apache.spark.sql.execution.FileSourceScanExec.copy$default$9()Z
```

I think they definitely change the constructor signature of `FileSourceScanExec`.

For `org.apache.spark.sql.execution.DataSourceScanExec`, I suspect that it is same reason. But this error looks harder to workaround.

**Comment by viirya** [comment]
BTW, is the Scala version matched between DBR and Comet?

**Comment by SemyonSinchenko** [comment]
DBR 13.3 [uses](https://docs.databricks.com/en/release-notes/runtime/13.3lts.html#system-environment) 2.12.15; Comet uses 2.12.17... May the problem be here? I can try to build comet with 2.12.17, just change in one line in `pom.xml`
